# Generated by Django 4.2.4 on 2024-02-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('file', models.BinaryField(blank=True, null=True)),
                ('error', models.BooleanField(default=False)),
            ],
        ),
    ]
