# Generated by Django 4.2.4 on 2024-02-19 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.BinaryField()),
                ('time', models.DateTimeField()),
                ('segment_num', models.PositiveIntegerField()),
                ('segment_error', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transport.message')),
            ],
        ),
    ]
