# Generated by Django 4.2.4 on 2024-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(default='incognito', max_length=50),
        ),
    ]
