# Generated by Django 4.2.4 on 2024-04-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_message_file_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
